// Generated by scripts/utils/generate-color-mappings.ts
export interface ColorMapping {
  sourceFile: string;
  componentName: string;
  variants: {
    color: {
      file: string;
      colors: {
        primary: string;
        accent?: string;
      };
    };
    monochrome: {
      file: string;
    };
  };
}

export const COLOR_MAPPINGS: ColorMapping[] = [
  {
    sourceFile: "ts-color.svg",
    componentName: "TypeScript",
    variants: {
      color: {
        file: "ts-color.svg",
        colors: {
          primary: "#3178c6",
          accent: "#fff",
        },
      },
      monochrome: {
        file: "ts-neutral.svg",
      },
    },
  },
  {
    sourceFile: "react-color.svg",
    componentName: "React",
    variants: {
      color: {
        file: "react-color.svg",
        colors: {
          primary: "#00d8ff",
        },
      },
      monochrome: {
        file: "react.svg",
      },
    },
  },
  {
    sourceFile: "tailwind-color.svg",
    componentName: "Tailwind",
    variants: {
      color: {
        file: "tailwind-color.svg",
        colors: {
          primary: "url(#a)",
        },
      },
      monochrome: {
        file: "tailwind.svg",
      },
    },
  },
  {
    sourceFile: "firebase-color.svg",
    componentName: "Firebase",
    variants: {
      color: {
        file: "firebase-color.svg",
        colors: {
          primary: "#ffc24a",
        },
      },
      monochrome: {
        file: "firebase.svg",
      },
    },
  },
  {
    sourceFile: "figma-color.svg",
    componentName: "Figma",
    variants: {
      color: {
        file: "figma-color.svg",
        colors: {
          primary: "#19bcfe",
        },
      },
      monochrome: {
        file: "figma.svg",
      },
    },
  },
  {
    sourceFile: "framer-color.svg",
    componentName: "Framer",
    variants: {
      color: {
        file: "framer-color.svg",
        colors: {
          primary: "#05f",
          accent: "#fff",
        },
      },
      monochrome: {
        file: "framer.svg",
      },
    },
  },
  {
    sourceFile: "whop_logo_brandmark_orange.svg",
    componentName: "Whop",
    variants: {
      color: {
        file: "whop_logo_brandmark_orange.svg",
        colors: {
          primary: "#FA4616",
        },
      },
      monochrome: {
        file: "whop_logo_brandmark_white.svg",
      },
    },
  },
];
